### PR TITLE
Fix error messages that contain "(" from being parsed incorrectly

### LINKED ISSUE #14: snazzy gives incorrect message for "Missing '()' invoking a constructor"
I've been all over the place with this issue, posting on [standard](https://github.com/feross/standard/issues/725), then [ESLint](https://github.com/eslint/eslint/issues/7792), back to standard and now here 😆 

If I have the code:

```js
const onionoo = new Onionoo()
```

to create a new instance of the `Onionoo` class but leave off the brackets:

```js
const onionoo = new Onionoo
```

`standard` and ESLint give the error `Missing '()' invoking a constructor` but `snazzy` just returns `Missing '`:

```
$ standard
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/lukechilds/Dev/oss/onionoo-node-client/test/unit.js:14:19: Missing '()' invoking a constructor.

$ snazzy
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.

/Users/lukechilds/Dev/oss/onionoo-node-client/test/unit.js
  14:19  error  Missing '

✖ 1 problem
```

### PR DESCRIPTION
**Pull request by feross**
Fixes https://github.com/feross/snazzy/issues/14

### CODE REVIEW

**Comment by feross** [comment]
Merged, but please review. I may have made a mistake and could use an extra set of eyes. Regexes are always tricky.

**Comment by feross** [comment]
Released as 1.0.2

**Comment by Flet** [comment]
Cool will check in the morning. Go to bed! :)

**Comment by feross** [comment]
@Flet On it! 😴

**Review by Flet — COMMENTED** [review]
Looks good! I added a test to cover parens for good measure.

**Pull request merged**
